<a href="https://colab.research.google.com/github/SandhyaRani1518/DL-projects/blob/main/NumPy_Full_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy in Python — Full Course (Basics → Advanced)

#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

Sections:
1. What is NumPy and Why use it
2. Speed comparison (list vs numpy)
3. Creating arrays
4. Array attributes & indexing
5. Mathematical operations
6. Useful array methods
7. Broadcasting & Reshaping
8. Combining, Splitting & Sorting
9. Advanced tricks (boolean indexing, matrix multiplication)
10. Summary

Run cells sequentially.

## 1) What is NumPy and Why use it

NumPy (Numerical Python) is a core Python library used for scientific computing.
- Fast and memory efficient compared to Python lists
- Provides ndarray: n-dimensional array object
- Supports vectorized operations (no Python loops)


## 2) Speed comparison: Python list vs NumPy array

In [ ]:
import numpy as np      #alias ---> np
import time

L = list(range(10000000))
start = time.time()
res = [x*2 for x in L]
list_time = time.time()-start

A = np.arange(10000000)
start = time.time()
res = A * 2
np_time = time.time()-start


list_time, np_time

(0.5632836818695068, 0.1868438720703125)

## 3) Creating NumPy arrays

Examples: from lists, zeros, ones, arange, linspace, eye, random

In [ ]:
import numpy as np
# From list
arr1 = np.array([1,2,3,4,5])

arr1


# Built-in methods
zeros = np.zeros((3,3))
ones = np.ones((2,4))
ar = np.arange(2,11,2)
lin = np.linspace(0,2,5)
iden = np.eye(4)


# Random

randf = np.random.rand(2,3)
randint = np.random.randint(1,100, size=(3,3))

ar

array([ 2.,  4.,  6.,  8., 10.])

## 4) Array attributes & Indexing

- `.shape`, `.size`, `.ndim`
- Indexing and slicing examples

In [ ]:
import numpy as np

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])

arr_shape = arr.shape
arr_size = arr.size
arr_ndim = arr.ndim

# indexing and slicing example

item = arr[0,1]
sub = arr[1:,1:]
col2 = arr[:,1]
row3 = arr[2,:]

arr_shape, arr_size, arr_ndim, item, sub, col2, row3

((3, 3),
 9,
 2,
 np.int64(20),
 array([[50, 60],
        [80, 90]]),
 array([20, 50, 80]),
 array([70, 80, 90]))

## 5) Mathematical Operations (vectorized)

Add, multiply, power, sqrt, sum etc.

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

add = a + b
sub = a - b
mul = a * b
sq = a ** 2
sqrt_b = np.sqrt(b)
sum_a = np.sum(a)


np.int64(6)

## 6) Useful Array Methods: min, max, mean, median, std, axis operations

In [ ]:
import numpy as np

arr = np.array([[10,20,30],[40,50,60]])

mins = np.min(arr)
maxs = np.max(arr)
mean_arr = np.mean(arr)
median_arr = np.median(arr)
std_arr = np.std(arr)

col_sum = np.sum(arr,axis=0)
row_sum = np.sum(arr, axis=1)

row_sum

array([ 60, 150])

## 7) Broadcasting & Reshaping

- Broadcasting example: add scalar to array
- Reshape and flatten

In [ ]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

add_scalar = arr + 10

a = np.arange(12)

resh = a.reshape(3,4)

flat = resh.flatten()

resh, flat

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))

## 8) Combining, Splitting & Sorting

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

concat = np.concatenate((a,b))
vstack = np.vstack((a,b))
hstack = np.hstack((a,b))

arr = np.array([10,210,30, 140,50,60])
splits = np.split(arr,2)
sorted_arr = np.sort(arr)

sorted_arr.tolist()

[10, 30, 50, 60, 140, 210]

## 9) Advanced Tricks: Boolean indexing, unique, dot (matrix multiply)

In [ ]:
import numpy as np

arr = np.arange(10)

filtered = arr[arr>5]

arr1 = np.array([1,1,2,3,4, 4, 5, 5])

unique_vals = np.unique(arr1)

filtered, unique_vals

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

matmaul = np.dot(A,B)

matmaul.tolist()

[[19, 22], [43, 50]]

## 10) Summary

- NumPy is essential for data science and ML.
- Key topics: arrays, indexing, vectorized ops, broadcasting, reshaping, matrix ops.

Next steps: Learn Pandas and Matplotlib to analyze and visualize data.